book:
  title: AI-NEPI Conference Proceedings - Enhanced Edition
  author:
  - "Gerd Gra\xDFhoff"
  - "Adrian W\xFCthrich"
  - Arno Simon
  date: '2025'
  chapters:
  - index.qmd
  - chapter_ai-nepi_001.qmd
  - chapter_ai-nepi_003.qmd
  - chapter_ai-nepi_004.qmd
  - chapter_ai-nepi_005.qmd
  - chapter_ai-nepi_006.qmd
  - chapter_ai-nepi_007.qmd
  - chapter_ai-nepi_008.qmd
  - chapter_ai-nepi_009.qmd
  - chapter_ai-nepi_010.qmd
  - chapter_ai-nepi_011.qmd
  - chapter_ai-nepi_012.qmd
  - chapter_ai-nepi_015.qmd
  - chapter_ai-nepi_016.qmd
  - chapter_ai-nepi_017.qmd
  - chapter_ai-nepi_018.qmd
  - chapter_ai-nepi_020.qmd
  - chapter_ai-nepi_021.qmd
format:
  html:
    theme: sandstone
    code-fold: true
    page-layout: full
project:
  type: book
  output-dir: docs
