book:
  title: "Large Language Models for History, Philosophy and Sociology of Science - Workshop Proceedings"
  author:
  - "Gerd Graßhoff"
  - "Adrian Wüthrich"
  - "Arno Simons"
  - "Michael Zichert"
  date: '2025-07-31'
  chapters:
  - index.qmd
  - chapter_ai-nepi_001.qmd
  - chapter_ai-nepi_003.qmd
  - chapter_ai-nepi_004.qmd
  - chapter_ai-nepi_005.qmd
  - chapter_ai-nepi_006.qmd
  - chapter_ai-nepi_007.qmd
  - chapter_ai-nepi_008.qmd
  - chapter_ai-nepi_009.qmd
  - chapter_ai-nepi_010.qmd
  - chapter_ai-nepi_011.qmd
  - chapter_ai-nepi_012.qmd
  - chapter_ai-nepi_015.qmd
  - chapter_ai-nepi_016.qmd
  - chapter_ai-nepi_017.qmd
  - chapter_ai-nepi_018.qmd
  - chapter_ai-nepi_019.qmd
  - chapter_ai-nepi_021.qmd

format:
  html:
    theme: sandstone
    code-fold: true
    css: styles.css
    toc: true
    toc-location: right
    number-sections: true
    number-depth: 3
    mainfont: "Crimson Text"
    fontsize: 1.1em
    linestretch: 1.5

project:
  type: book
  output-dir: docs
